import { defineConfig } from "vite";
import { svelte } from "@sveltejs/vite-plugin-svelte";
import path from "path";
import fs from "fs";

// Emit a sibling .d.ts for each bundle. Consumers that type-check imported
// JavaScript (e.g. tsconfig `checkJs`) resolve types from the declaration
// and never type-check the minified bundle itself — the bundle is imported
// for its custom-element-registration side effect only, and checking it
// produces thousands of meaningless diagnostics. Since dist/ is committed
// in this repo, downstream consumers (rcvis et al.) get this for free.
function emitBundleDts() {
  return {
    name: "emit-bundle-dts",
    writeBundle(options: { dir?: string }, bundle: Record<string, { fileName: string }>) {
      const outDir = options.dir ?? "dist";
      for (const file of Object.values(bundle)) {
        if (file.fileName.endsWith(".es.js")) {
          const dts = file.fileName.replace(/\.js$/, ".d.ts");
          fs.writeFileSync(
            path.join(outDir, dts),
            "// Auto-generated by emitBundleDts (vite.config.ts). Shadows the\n" +
            "// bundle so consumers' type checkers skip it entirely.\n" +
            "export {};\n"
          );
        }
      }
    },
  };
}

export default defineConfig({
  server: {
    port: 4000
  },
  plugins: [svelte({
    compilerOptions: {
      customElement: true
    }
  }), emitBundleDts()],
  build: {
    copyPublicDir: true,
    lib: {
      entry: {
        'pie-chart': 'src/lib/pie-chart.js',
      },
      formats: ["es"],
    },
    rollupOptions: {
      external: [],
      output: {
        globals: {},
        entryFileNames: '[name].es.js',
        chunkFileNames: 'custom-element-helper.js',
        format: 'es'
      },
      preserveEntrySignatures: "strict",
    },
  },
  resolve: {
    alias: {
      $components: path.resolve('src/lib'),
      $lib: path.resolve('src/lib'),
    },
  },
});
